apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "devops-practical-chart.fullname" . }}-mongodb
spec:
  serviceName: {{ include "devops-practical-chart.fullname" . }}-mongodb
  replicas: {{ .Values.mongodb.replicas }}
  selector:
    matchLabels:
      app: {{ include "devops-practical-chart.fullname" . }}-mongodb
  template:
    metadata:
      labels:
        app: {{ include "devops-practical-chart.fullname" . }}-mongodb
    spec:
      containers:
        - name: mongodb
          image: {{ .Values.mongodb.image.repository }}:{{ .Values.mongodb.image.tag }}
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-persistent-storage
              mountPath: /data/db
  volumeClaimTemplates:
    - metadata:
        name: mongo-persistent-storage
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
