apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-practical-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops-practical-app
  template:
    metadata:
      labels:
        app: devops-practical-app
    spec:
      containers:
      - name: app
        image: devops-practical-app:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
        env:
        - name: MONGODB_URL
          value: "mongodb://mongo:27017/yourdatabase"
